# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: CoursePlus API
  description: CoursePlus API, 返回值的json格式是默认用data包起来的
  version: "1.0.0"
# the domain of the service
host: 120.26.65.167:8080
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /carousel:
    get:
      summary: Carousel type
      description: 获取轮播图列表
      tags:
        - Carousel
      responses:
        200:
          description: 轮播图列表
          schema:
            type: array
            items:
              $ref: '#/definitions/Carousel'
  /course/search:
    get:
      summary: Course type
      description: 获取课程列表
      parameters:
        - name: offset
          in: query
          type: integer
          format: int32
          description: 偏移，默认是0.
        - name: limit
          in: query
          type: integer
          format: int32
          description: 返回的数量，默认是5.
        - name: major_id
          in: query
          type: integer
          format: int32
          description: 专业id，不传表示精品课程
      tags:
        - Course
      responses:
        200:
          description: 课程列表
          schema:
            $ref: '#/definitions/Courses'

  /course/period:
    get:
      summary: Period type
      description: 获取课时
      parameters:
        - name: course_id
          in: query
          type: integer
          format: int32
          description: 课程id
      tags:
        - Period
      responses:
        200:
          description: 课时列表
          schema:
            type: array
            items:
              $ref: '#/definitions/Period'
definitions:
  
  Carousel:
    type: object
    properties:
      id:
        type: integer
        format: int32
        description: 轮播图id
      img_url:
        type: string
        description: 图片地址
      link_url:
        type: string
        description: 跳转地址
  School:
    type: object
    properties:
      id: 
        type: integer
        format: int32
        description: 学校id
      name:
        type: string
        description: 学校名
  Major:
    type: object
    properties:
      id:
        type: integer
        format: int32
        description: 专业id
      code: 
        type: string
        description: 专业代码
      name:
        type: string
        description: 专业名
      school:
        type: object
        $ref: '#/definitions/School'
      category:
        type: object
        $ref: '#/definitions/Major_Category'
  Major_Category:
    type: object
    description: 专业大类
    properties:
      id: 
        type: integer
        format: int32
        description: 大类id
      code:
        type: string
        description: 大类代码
      name:
        type: string
        description: 大类名称
  Course:
    type: object
    properties: 
      id:
        type: integer
        format: int32
        description: 课程id
      name: 
        type: string
        description: 课程名
      teacher:
        type: object
        $ref: '#/definitions/Teacher'
      major:
        type: object
        $ref: '#/definitions/Major'
        description: 专业
      code:
        type: string
        description: 课程编号
      star:
        type: number
        format: double
        description: 课程评分星级
  Courses:
    type: object
    properties:
      offset:
        type: integer
        format: int32
        description: 偏移
      limit:
        type: integer
        format: int32
        description: 限制数量
      count:
        type: integer
        format: int32
        description: 课程总数量
      list:
        type: array
        items:
          $ref: '#/definitions/Course'
  Period:
    type: object
    description: 课时
    properties:
      id: 
        type: integer
        description: 课时id
      course_id: 
        type: integer
        description: 课程id
      name:
        type: string
        description: 课时名称
      date: 
        type: string
        description: 课时日期
      price:
        type: number
        format: double
        description: 课时价格
  Teacher:
    type: object 
    properties: 
      id: 
        type: integer
        format: int32
        description: 用户id
      name:
        type: string
        description: 昵称（姓名）
      img_url:
        type: string
        description: 头像地址 
      account:
        type: string
        description: 账号
      sex:
        type: integer
        description: 1男 2女 3未知
      introduction:
        type: string
        description: 红字（如2016 专业课排名第二）
      description:
        type: string
        description: 黑字(具体的得分信息)
      education:
        type: string
        description: 学历(如南京大学2016级环境学院研究生)
  
  
  
  
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
