# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: CoursePlus API
  description: CoursePlus API, 返回值的json格式是默认用data包起来
  version: "1.0.0"
# the domain of the service
host: 120.26.65.167:8080
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  
   /user/changePassword:
    post:
      summary: 修改密码
      description: 修改密码
      tags:
        - User
      parameters:
        - name: json
          in: body
          description: 用户密码信息
          required: true
          schema:
            properties:
              old_password:
                type: string
                description: 旧密码，需加密
              new_password:
                type: string
                description: 新密码，需加密
              
      responses:
        200:
          description: 修改结果，直接看是否有error，有error代表失败，没有就代表成功

   /user/updateInfo:
    post:
      summary: 修改个人资料
      description: 修改个人资料
      tags:
        - User
      parameters:
        - name: json
          in: body
          description: 用户信息, 内容均可选
          required: true
          schema:
            properties:
              nickname:
                type: string
                description: 用户昵称
              gender:
                type: integer
                format: int4
                description: 1男 2女 3未知
              img_url:
                type: string
                description: 头像的key，需要提前使用七牛的插件上传
 
      responses:
        200:
          description: 若成功，返回最新的个人信息，否则有error
          schema:
            $ref: "#/definitions/User"

          
   /user/sendVerifyCode:
    get:
      summary: verifyCode
      description: 发送验证码
      tags:
        - User
      parameters:
        - name: phone
          in: query
          description: 手机号码
          required: true
          type: string
      responses:
        200:
          description: 发送结果，直接看是否有error，有error代表失败，没有就代表成功
              
   /user/register:
    post:
      summary: 注册
      description: 用户注册
      tags:
        - User
      parameters:
        - name: json
          in: body
          description: 用户信息
          required: true
          schema:
            properties:
              username:
                type: string
                description: 用户名，手机号
              password:
                type: string
                description: 用户密码，需要加密
              verify_code:
                type: string
                description: 验证码
              nickname:
                type: string
                description: 用户昵称
      responses:
        200:
          description: 注册结果，直接看是否有error，有error代表失败，没有就代表成功

   /user/login:
    post:
      summary: 登录
      description: 用户登录
      tags:
        - User
      parameters:
        - name: json
          in: body
          description: 登录信息
          required: true
          schema:
            properties:
              username:
                type: string
                description: 用户名，手机号
              password:
                type: string
                description: 用户密码，需要加密
      responses:
        200:
          description: 登录结果，若登录成功会返回用户信息并且Cookie
          schema:
            $ref: "#/definitions/User"
  
   /carousel:
    get:
      summary: Carousel type
      description: 获取轮播图列表
      tags:
        - Carousel
      responses:
        200:
          description: 轮播图列表
          schema:
            type: array
            items:
              $ref: '#/definitions/Carousel'

   /school:
    get:
      summary: School type
      description: 获取学校列表
      tags:
        - School
      responses:
        200:
          description: 学校列表
          schema:
            type: array
            items:
              $ref: '#/definitions/School'
    
   /school/major:
    get:
      summary: Major type
      description: 获取学校的专业列表
      tags:
        - School
      parameters:
        - name: school_id
          in: query
          type: integer
          format: int32
          description: 学校id
          required: true
      responses:
        200:
          description: 专业列表
          schema:
            type: array
            items:
              $ref: '#/definitions/Major'
   
   /course/search:
    get:
      summary: Course type
      description: 获取课程列表
      parameters:
        - name: offset
          in: query
          type: integer
          format: int32
          description: 偏移，默认是0.
        - name: limit
          in: query
          type: integer
          format: int32
          description: 返回的数量，默认是5.
        - name: major_id
          in: query
          type: integer
          format: int32
          description: 专业id(不传表示获取学校的课程)
        - name: school_id
          in: query
          type: integer
          format: int32
          description: 学校id(专业id和学校id都不传表示精品课程)
      tags:
        - Course
      responses:
        200:
          description: 课程列表
          schema:
            $ref: '#/definitions/Courses'
            
   
   /course/documents:
    get:
      summary: 资料列表
      description: 获取资料列表
      parameters:
        - name: offset
          in: query
          type: integer
          format: int32
          description: 偏移，默认是0.
        - name: limit
          in: query
          type: integer
          format: int32
          description: 返回的数量，默认是5.
        - name: course_id
          in: query
          type: integer
          format: int32
          description: 课程id
      tags:
        - Course
      responses:
        200:
          description: 资料列表
          schema:
            $ref: '#/definitions/Documents'
  
   /course/previewDocument:
    get:
      summary: 预览文档
      description: 获取文档预览信息，注意，需要根据用户购买状态返回完整的预览地址或者是部分的预览地址
      parameters:
        - name: id
          in: query
          type: integer
          format: int32
          description: 文档id
          required: true
      tags:
        - Course
      responses:
        200:
          description: 预览信息
          schema:
           properties:
            preview_url:
              type: string
              description: 预览地址，若购买返回完整的
            is_buy:
              type: integer
              format: int8
              description: 是否购买，0或1
            
   /course/period:
    get:
      summary: Period type
      description: 获取课时
      parameters:
        - name: course_id
          in: query
          type: integer
          format: int32
          description: 课程id
          required: true
      tags:
        - Course
      responses:
        200:
          description: 课时列表
          schema:
            type: array
            items:
              $ref: '#/definitions/Period'  

   /pay/period:
    get:
      summary: 购买单独课时
      description: 购买单独课时，获取charge对象
      parameters:
        - name: id
          in: query
          type: integer
          format: int32
          description: 课时id
          required: true
        - name: channel
          in: query
          type: string
          description: 支付手段 目前就支付宝 alipay_pc_direct
          required: true
      tags:
        - Pay
      responses:
        200:
          description: ping++的charge对象，不用关心具体内容。
  
   /pay/document:
    get:
      summary: 购买单门资料
      description: 购买单门资料，获取charge对象
      parameters:
        - name: id
          in: query
          type: integer
          format: int32
          description: 资料id
          required: true
        - name: channel
          in: query
          type: string
          description: 支付手段 目前就支付宝 alipay_pc_direct
          required: true
      tags:
        - Pay
      responses:
        200:
          description: ping++的charge对象，不用关心具体内容。
          
   /course/qualityComment:
    get:
      summary: QualityComment type
      description: 获取首页优质评价列表
      tags:
        - Course
      responses:
        200:
          description: 评价列表
          schema:
            type: array
            items:
              $ref: '#/definitions/QualityComment'  
   
   /course/courseDetail:
    get:
      summary: 获取课程详情
      parameters:
        - name: id
          in: query
          type: integer
          format: int32
          description: 课程id
      description: 获取课程详情，除了课程列表买断价格，包括现价、原价，需要根据用户登录情况以及用户购买情况区别计算
      tags:
        - Course
      responses:
        200:
          description: 课程详情
          schema:
              $ref: '#/definitions/CourseDetail'  
      
   /course/periodDetail:
    get:
      summary: 获取课时详情
      parameters:
        - name: id
          in: query
          type: integer
          format: int32
          description: 课时id
      description: 获取课程详情，除了课程列表买断价格，包括现价、原价，需要根据用户登录情况以及用户购买情况区别计算
      tags:
        - Course
      responses:
        200:
          description: 课时的内容
          schema:
            properties:
              live:
                $ref: '#/definitions/Live'
              content:
                type: string
                description: 富文本html
   /course/liveDetail:
    get:
      summary: 直播页获取直播相关信息
      parameters:
        - name: id
          in: query
          type: integer
          format: int32
          description: 直播id
      description: 获取直播间相关信息
      tags:
        - Course
      responses:
        200:
          description: 直播信息
          schema:
            properties:
              live:
                $ref: '#/definitions/SimpleLive'
              course:
                $ref: '#/definitions/SimpleCourse'
              period:
                $ref: '#/definitions/SimplePeriod'
   /teacher/qualityTeacher:
    get:
      summary: Teacher type
      description: 获取优质教师列表
      tags:
        - Teacher
      responses:
        200:
          description: 教师列表
          schema:
            type: array
            items:
              $ref: '#/definitions/Teacher'     
              
    
    
              
definitions:
  Carousel:
    type: object
    properties:
      id:
        type: integer
        format: int32
        description: 轮播图id
      img_url:
        type: string
        description: 图片地址
      link_url:
        type: string
        description: 跳转地址
        
        
  School:
    type: object
    properties:
      id: 
        type: integer
        format: int32
        description: 学校id
      name:
        type: string
        description: 学校名
      img_url:
        type: string
        description: 学校logo
  
  MajorCategory:
    type: object
    description: 专业大类
    properties:
      id: 
        type: integer
        format: int32
        description: 大类id
      code:
        type: string
        description: 大类代码
      name:
        type: string
        description: 大类名称
  
  SimpleMajor:
    type: object
    properties:
      id:
        type: integer
        format: int32
        description: 专业id
      code:
        type: string
        description: 专业代码
      name:
        type: string
        description: 专业名
      school:
        $ref: '#/definitions/School'
        
  Major:
    type: object
    properties:
      id:
        type: integer
        format: int32
        description: 专业id
      code: 
        type: string
        description: 专业代码
      name:
        type: string
        description: 专业名
      school:
        $ref: '#/definitions/School'
      category:
        $ref: '#/definitions/MajorCategory'
  
  Subject:
    type: object
    properties:
      id:
        type: integer
        format: int32
        description: 科目id
      code:
        type: string
        description: 科目代码
      name: 
        type: string
        description: 科目名
      img_url:
        type: string
        description: 课程背景图片url
        
  Teacher:
    type: object 
    properties: 
      id: 
        type: integer
        format: int32
        description: 用户id
      name:
        type: string
        description: 昵称（姓名）
      img_url:
        type: string
        description: 头像地址 
      account:
        type: string
        description: 账号
      gender:
        type: integer
        description: 1男 2女 3未知
      introduction:
        type: string
        description: 红字（如2016 专业课排名第二）
      description:
        type: string
        description: 黑字(具体的得分信息)
      education:
        type: string
        description: 学历(如南京大学2016级环境学院研究生)
        
  SimpleCourse:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      code:
        type: string
      major:
        $ref: '#/definitions/SimpleMajor'
        
      teacher:
        $ref: '#/definitions/SimpleTeacher'
        
  SimpleTeacher:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        img_url: 
          type: string
          
  Course:
    type: object
    properties: 
      id:
        type: integer
        format: int32
        description: 课程id
      subject:
        $ref: '#/definitions/Subject'
      star:
        type: number
        format: double
        description: 课程评分星级
      buyer_num:
        type: integer
        description: 购买人数
      name:
        type: string
        description: 课程名
      teacher:
        $ref: '#/definitions/Teacher'
      major:
        $ref: '#/definitions/Major'
      
  CourseDetail:
    type: object
    properties: 
      id:
        type: integer
        format: int32
        description: 课程id
      subject:
        $ref: '#/definitions/Subject'
      star:
        type: number
        format: double
        description: 课程评分星级
      buyer_num:
        type: integer
        description: 购买人数
      origin_price:
        type: integer
        format: int32
        description: 原价，单位分，需要根据用户当前已购买的课时结算
      currentPrice:
        type: integer
        format: int32
        description:
                  现价，单位分，需要用定好的买断价减去已购买的课程乘以折扣
      is_buy:
        type: integer
        format: int8
        description: 是否买断， 0或1
        
      teacher:
        $ref: '#/definitions/Teacher'
      major:
        $ref: '#/definitions/Major'
        
        
  Courses:
    type: object
    properties:
      offset:
        type: integer
        format: int32
        description: 偏移
      limit:
        type: integer
        format: int32
        description: 限制数量
      count:
        type: integer
        format: int32
        description: 课程总数量
      list:
        type: array
        items:
          $ref: '#/definitions/Course'
      
  Period:
    type: object
    description: 课时
    properties:
      id: 
        type: integer
        description: 课时id
      course_id: 
        type: integer
        description: 课程id
      number:
        type: integer
        description: 课时编号
      name:
        type: string
        description: 课时名称
      date: 
        type: string
        description: 课时日期
      price:
        type: number
        format: double
        description: 课时价格
      is_buy:
        type: integer
        format: int8
        description: 是否购买， 0或1
  SimplePeriod:
    type: object
    description: 课时
    properties:
      id:
        type: integer
        description: id
      name:
        type: string
        description: 名称
      number:
        type: integer
        description: 课时编号
  QualityComment:
    type: object
    description: 首页的优质的评论
    properties:
      id: 
        type: integer
      course:
        $ref: '#/definitions/SimpleCourse'
      content:
        type: string
        description: 内容
      user_name:
        type: string
        description: 评价者用户名
        
  Live:
    type: object
    description: 视频详情
    properties:
      id:
        type: integer
        format: int32
        description: 视频id
      start_time:
        type: string
        description: 开始时间 格式
      state:  
        type: string
        description: 视频状态 CODED、CODING、ING、BEFORE
      preview_url:
        type: string
        description: 预览地址 10分钟视频
      complete_url:
        type: string
        description: 完整地址，注意如果没有购买不要返回
      live_url:
        type: string
        description: 直播地址
  SimpleLive:
    type: object
    description: 简单live
    properties:
      id: 
        type: integer
        description: id
      live_url:
        type: string
        description: 直播地址
  Document:
    type: object
    description: 资料信息
    properties:
      id: 
        type: integer
      name:
        type: string
        description: 资料名称
      price:
        type: integer
        format: int32
        description: 资料价格  0表示赠送
      origin_price:
        type: integer
        format: int32
        description: 资料原价
      cover_path:
        type: string
        description: 封面地址
      buyer_num:
        type: integer
        format: int32
        description: 购买数量
  
  
  Documents:
    type: object
    properties:
      offset:
        type: integer
        description: 偏移
      limit:
        type: integer
        description: 限制数量
      count:
        type: integer
        description: 一共的数量
      list:
        type: array
        items:
          $ref: '#/definitions/Document'
          
  Teachers:
    type: object
    properties:
      offset:
        type: integer
        description: 偏移
      limit:
        type: integer
        description: 限制数量
      count:
        type: integer
        description: 一共的数量
      list:
        type: array
        items:
          $ref: '#/definitions/Teacher'
          

  User:
    type: object
    properties:
      id:
        type: integer
        format: int32
        description: 用户id
      account:
        type: string
        description: 账户名（手机号）
      img_url:
        type: string
        description: 头像地址
      name:
        type: string
        description: 昵称
      gender:
        type: integer
        format: int4
        description: 1男 2女 3未知
        
  Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
          
    